services:
  keydb-server:
    image: eqalpha/keydb:latest
    container_name: keydb-container
    ports:
      - 8991:6379
    volumes:
      - ./keydb.conf:/etc/keydb/keydb.conf

volumes:
  db-data:

secrets:
  db-credentials:
    file: secrets.txt
