services:
  redis-server:
    image: redis/redis-stack:latest
    # image: redis-server-image
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     CONF_PATH: .docker/redis/redis.conf
    #     ACL_PATH: .docker/redis/users.acl
    container_name: redis-container
    networks:
      net0:
        aliases:
          - redis.service
    user: root
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ${HOSTDIR_CONF}:${WORKDIR_CONF}:rwx
      - ${HOSTDIR_LOCAL_DATA}:${WORKDIR_LOCAL_DATA}:rwx
    env_file:
      - path: .env
        required: true
    # command: >
    #   redis-server --requirepass s1mpliky

  # mongodb-server:
  #   image: mongo:latest
  #   container_name: mongodb-for-redis
  #   networks:
  #     net0:
  #       aliases:
  #         - mongodb.service
  #   user: root
  #   ports:
  #     - 8998:27017
  #   volumes:
  #     - ./.docker/mongodata:/data/db
  #   env_file:
  #     - path: .env
  #       required: true

# volumes:
#   .docker:
#     external: true

# secrets:
#   user-acl:
#     file: ./server/keydb/users.acl

networks:
  net0:
    driver: bridge
