services:
  redis-server:
    image: redis:latest
    container_name: redis-container
    networks:
      net0:
        aliases:
          - "redis.service"
    user: root
    ports:
      - 8997:6379
    volumes:
      - ./.docker/redis:/usr/local/etc/redis
      - ./.docker/data:/data

  mongodb-server:
    image: mongo:latest
    container_name: "mongodb-for-redis"
    networks:
      net0:
        aliases:
          - "mongodb.service"
    user: root
    ports:
      - 8998:27017
    volumes:
      - ./.docker/mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: s1mpliky

volumes:
  .docker:
    external: true

# secrets:
#   user-acl:
#     file: ./server/keydb/users.acl

networks:
  net0:
    driver: bridge
